services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo11-tracker
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./models:/app/models
      - ./configs:/app/configs  # Instead of /app/sam2/configs

    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - SAM2_BUILD_CUDA=0
      - SAM2_BUILD_ALLOW_ERRORS=1
    tty: true
    restart: always
    command: python -u -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload

  fiftyone:
    build:
      context: .
      dockerfile: Dockerfile_fiftyone
    volumes:
      - ./fiftyone_output:/app/fiftyone_output
      - ./output:/app/output
    ports:
      - "5151:5151"
    environment:
      - FIFTYONE_DATABASE_URI=mongodb://mongo:27017
      - FIFTYONE_LOGGING_LEVEL=INFO
    command: python /app/fiftyone_app.py
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null 

volumes:
  mongo-data: