services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo11-tracker
    volumes:
      - ./input:/app/input        # Map input directory
      - ./output:/app/output      # Map output directory
      - ./models:/app/models      # Map models directory
    ports:
      - "8080:8080"               # Expose FastAPI port
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: python -u -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload
