services:

  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: yolo11-tracker
    volumes:
      # Map input, output, models directory
      - ./input:/app/input 
      - ./output:/app/output
      - ./models:/app/models
      # Persistent cache directories below - download once
      - ./models/easyocr:/root/.EasyOCR/model 
      - ./models/paddleocr:/root/.paddleocr/whl   
      - ./models/mediapipe:/usr/local/lib/python3.11/site-packages/mediapipe/modules
      - ./models/torch:/root/.cache/torch
      # # Mount pip cache directory for faster image builds
      - pip-cache:/pip_cache      
    ports:
      - "8080:8080"               # Expose FastAPI port
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - PIP_CACHE_DIR=/pip_cache
    tty: true
    restart: always
    command: python -u -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - redis

  #fiftyone:
  #  build:
  #    context: ./fiftyone
  #    dockerfile: Dockerfile
  #  volumes:
  #    - ./fiftyone_output:/app/output/fiftyone_output  # Use a separate volume for FiftyOne
  #    - ./output:/app/output                    # Map output directory
  #  ports:
  #    - "5151:5151"
  #  environment:
  #    - FIFTYONE_DATABASE_URI=mongodb://mongo:27017
  #    - FIFTYONE_LOGGING_LEVEL=INFO
  #  command: python /app/fiftyone_app.py
  #  depends_on:
  #    - mongo
  
  rq_worker:
    build:
      context: ./rq_worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - QUEUE_NAME=detection-inspection-queue
      - LOG_LEVEL=WARNING # or DEBUG, INFO, WARNING, ERROR, CRITICAL
    depends_on:
      - redis
      - fastapi
    command: ["python", "rq_worker.py"]
    # restart: on-failure
    stop_signal: SIGTERM  # Graceful shutdown signal

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "warning"]
    stop_signal: SIGTERM  # Graceful shutdown signal
    
  #mongo:
  #  image: mongo:latest
  #  ports:
  #    - "27017:27017"
  #  volumes:
  #    - mongo-data:/data/db   # Correct path for MongoDB
  #  command: mongod --quiet --logpath /dev/null 

volumes:
  mongo-data:
  pip-cache:
